config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  root to: 'cats#index'
  resources :cats do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
  get 'comments/new'
  post 'like/:id' => 'likes#create', as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'
  get '/cat/prefecture', to: "cats#prefecture"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def previous
    Cat.where("id < ?", self.id).order("id DESC").first
  end
  def next
    Cat.where("id > ?", self.id).order("id ASC").first
  end

end

app/models/cat.rb
class Cat < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  belongs_to :user
  has_many_attached :images
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  
  with_options presence: true do
    validates :prefecture_id
    validates :area
    validates :images
  end
  validates :prefecture_id, numericality: { other_than: 0, message: 'は--以外を選んでください' }

  def self.search(search)
    if search != ""
      Cat.where('area LIKE(?) OR message LIKE(?) OR place LIKE(?)',
                 "%#{search}%", "%#{search}%", "%#{search}%")
    else
      Cat.all
    end
  end
  
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :cat

  validates :text, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :cat

  validates :user_id, {presence: true}
  validates :cat_id, {presence: true}
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base

  self.data = [
               {id: 0, name: '--'}, {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, 
               {id: 3, name: '岩手県'}, {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, 
               {id: 6, name: '山形県'}, {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, 
               {id: 9, name: '栃木県'}, {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, 
               {id: 12, name: '千葉県'}, {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, 
               {id: 15, name: '新潟県'}, {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, 
               {id: 18, name: '福井県'}, {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, 
               {id: 21, name: '岐阜県'}, {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, 
               {id: 24, name: '三重県'}, {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, 
               {id: 27, name: '大阪府'}, {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, 
               {id: 30, name: '和歌山県'}, {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, 
               {id: 33, name: '岡山県'}, {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, 
               {id: 36, name: '徳島県'}, {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, 
               {id: 39, name: '高知県'}, {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, 
               {id: 42, name: '長崎県'}, {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, 
               {id: 45, name: '宮崎県'}, {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
  ]
  include ActiveHash::Associations
  has_many :cats
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, uniqueness: true
  VALID_PASSWORD_REGEX = /([0-9].*[a-zA-Z]|[a-zA-Z].*[0-9])/.freeze
  validates :password, format: { with: VALID_PASSWORD_REGEX, message: 'は英語と数字を使用してください' }
  validates :nickname, presence: true

  has_many :cats
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  def self.guest
    find_or_create_by!(nickname: 'ゲスト', email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end

  def liked_by?(cat_id)
    likes.where(cat_id: cat_id).exists?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
before_action :authenticate_user!, except: [:index, :show]
before_action :set_cat ,only: [:show, :edit, :update, :destroy]
before_action :search_prefecture_cat, only: [:index, :prefecture, :hashtag, :search, :show]

  def index
    @cats = Cat.all.order(created_at: :desc).page(params[:page]).per(9) 
    @likes_count = Like.where(cat_id: @cats.ids)
  end

  def new
    @cat = Cat.new
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @cat.comments.includes(:user)
    @likes_count = Like.where(cat_id: @cat.id)
  end

  def edit
  end

  def update
    if @cat.update(cat_params)
      redirect_to cat_path
    else
      render :edit
    end
  end

  def destroy  
    if @cat.destroy
      redirect_to root_path
    end
  end

  def search
    @cats = Cat.search(params[:keyword]).page(params[:page]).per(5)

  end

  def prefecture
    @cats = @q.result.page(params[:page]).per(5)
    prefecture_id = params[:q][:prefecture_id_eq]
    @prefecture = Prefecture.find_by(id: prefecture_id)
  end

  private

  def cat_params
    params.require(:cat).permit(:message, :prefecture_id, :area, :place, images: []).merge(user_id: current_user.id)
  end

  def set_cat
    @cat = Cat.find(params[:id])
  end

  def search_prefecture_cat
    @q = Cat.ransack(params[:q])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to "/cats/#{@comment.cat.id}" 
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    if @comment.destroy
      redirect_to "/cats/#{@comment.cat.id}" 
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, cat_id: params[:cat_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  
  def create
    Like.create(user_id: current_user.id, cat_id: params[:id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    Like.find_by(user_id: current_user.id, cat_id: params[:id]).destroy
    redirect_back(fallback_location: root_path)
  end

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :check_guest, only: :destroy

  def check_guest
    if resource.email == 'guest@example.com'
      redirect_to root_path, alert: 'ゲストユーザーは削除できません。'
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/cats/_cat.html.erb
<% @cats %>   
<div class="cat-show">
  <div class="cat-box">
    <h2 class="name">
      <%= cat.prefecture.name %> <%= cat.area %> <%= cat.place %>
    </h2>
      画像がたくさんある場合はスライドで見れるよ
    <div class='cat-img-content'>
      <% cat.images.each do |image|%>
        <%= image_tag image ,class:"cat-box-img" %>
      <% end %>
    </div>
    <div class= "cat-details">
      <%= link_to "詳しく見る",cat_path(cat.id), method: :get %>
    </div> 
</div>

app/views/cats/_like.html.erb
<% if current_user.liked_by?(cat.id) %>
  <td>
    <%= link_to destroy_like_path(cat), class: "like-link", method: :DELETE, remote: true do %>
      <i class="fa fa-heart like-btn-unlike"></i>
    <% end %>
  </td>
  <%= cat.likes.count %>
<% else %>
  <td>
    <%= link_to create_like_path(cat), calss: "like-link", method: :POST, remote: true do %>
      <i class="fa fa-heart like-btn"></i>
    <% end %>
    <%= cat.likes.count %>
  </td>
<% end %>

app/views/cats/edit.html.erb
<div class="cat-post-contents">
  <header class="cat-post-header">
    <%= link_to image_tag('nyaking-map.png' , size: '200x80'), "/" %>

  </header>
  <div class="cat-post-main">
    <h2 class="cat-post-title">投稿ページ</h2>
    <%= form_with model: @cat, local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>
    
    <div class="img-upload">
      <div class="weight-bold-text">
        画像 ※複数OK
        <span class="indispensable">必須</span> 
        <div class="click-upload">               
          <%= f.file_field :images, name: 'cat[images][]', id: 'cat-image' %>
        </div>
        <div class="image-list" id="image-list"></div>
      </div>      
    </div>
    
    <div class="nickname">
      <div class="cats-explain">
        <div class="weight-bold-text">
          メッセージ
        </div>
        <%= f.text_area :message, class:"cats-text", id:"cat-info",rows:"7" ,maxlength:"1000" %>
      </div>
    </div>

    <div class="area-detail">
      <div class="form">
        <div class="weight-bold-text">
          都道府県
          <span class="indispensable">必須</span>
          <span><%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"select-box", id:"prefecture"}) %></span>
        </div>
        
        <div class="weight-bold-text">
          市町村
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :area, class:"area-text", id:"cat-area" %>
        <div class="weight-bold-text">
          会える場所
        </div>
        <%= f.text_area :place, class:"place-text", id:"cat-place" %>
      </div>
    </div>
    <div class="post-btn-contents">
      <%= f.submit "変更する" ,class:"post-btn" %>
      <%=link_to 'もどる', cat_path, class:"back-btn" %>
    </div>
  </div>
  <% end %>

  <footer class="cats-post-footer">
    <ul class="menu">
    </ul>
    <%= link_to image_tag('nyaking-map.png' , size: '200x80'), "/" %>
    <p class="inc">
       ©︎Nyaking-map,Inc.
    </p>
  </footer>
</div>

app/views/cats/index.html.erb
<%= render "shared/header" %>
<div class='main'>
  <div class='title-contents'>
    <h2 class='service-title'>
      猫を愛する全ての人へ
    </h2>
    <p class='service-explain'>
      nyaking-mapは地域猫を通じてみんながつながっていく
    </p>
    <p class='service-explain'>
      コミュニティアプリです
    </p>
    <div class='store-btn'>
      <%#= link_to image_tag("https://linkmaker.itunes.apple.com/ja-jp/badge-lrg.svg?releaseDate=2011-09-21&kind=iossoftware&bubble=ios_apps", class:"apple-btn"), "#" %>
      <%#= link_to image_tag("dl-android.png", class:"google-btn"), "#" %>
    </div>
  </div>

  <div class='cat-contents'>
    <h2 class='title'>みんなで作ろう</h2>
    <%= link_to 'MAPPING!!', new_cat_path, class: "subtitle" %>
    <ul class='cat-lists'>
      <% if @cats.length >= 1 %>
        <% @cats.each do |cat| %>    
          <li class='list'>
            <%= link_to cat_path(cat.id), method: :get do %>
              <div class='cat-img-content' >
                <%= image_tag cat.images[0], class: "cat-img" %>
              </div>
              <div class='cat-info'>
                <h3 class='prefecture-name'>
                  <%= cat.prefecture.name %>
                </h3>
                <div class="area-name">
                  <div class="area-name">
                    <p><%= cat.area %></p>
                    <p><%= cat.user.nickname %> さん</p>
                  </div>
                </div>
                <tr>
                <% if user_signed_in? %>
                  <% if current_user.liked_by?(cat.id) %>
                    <td>
                      <%= link_to destroy_like_path(cat), class: "like-link", method: :DELETE do %>
                        <i class="fa fa-heart like-btn-unlike"></i>
                      <% end %>
                    </td>
                    <%= cat.likes.count %>
                  <% else %>
                    <td>
                      <%= link_to create_like_path(cat), calss: "like-link", method: :POST do %>
                        <i class="fa fa-heart like-btn"></i>
                      <% end %>
                      <%= cat.likes.count %>
                    </td>
                  <% end %>
                <% end %>
                </tr> 
              </div>
            <% end %>
          </li>
        <% end %>
      <% end %>
    </ul>
    <%= paginate @cats %>
  </div>

  <div class='how-to-contents'>
    <h2 class='title'>
      楽しみ方いろいろ
    </h2>
    <ul class='reason-lists'>
      <li class='list'>
        <%= image_tag "1.jpg", class:"list-pict" %>
        <span class='reason-list-number'>1</span>
        <h3 class='reason-list-text'>
          <span class='reason-list-blue-text'>投稿</span>
          でみんなに教えよう
        </h3>
        <p class='reason-list-description'>
          可愛い猫が近所にいるかも！！
        </p>
      </li>
      <li class='list'>
        <%= image_tag "10.jpg", class:"list-pict" %>
        <span class='reason-list-number'>2</span>
        <h3 class='reason-list-text'>
          <span class='reason-list-blue-text'>お出かけ</span>
          会いにいく？
        </h3>
        <p class='reason-list-description'>
          地域の看板猫に会えるかも！
        </p>
      </li>
      <li class='list'>
        <%= image_tag "13.jpg", class:"list-pict" %>
        <span class='reason-list-number'>3</span>
        <h3 class='reason-list-text'>
          周辺も
          <span class='reason-list-blue-text'>ぶらりお散歩</span>
        </h3>
        <p class='reason-list-description'>
          カフェなどの周辺情報も載せてね
        </p>
      </li>
    </ul>
  </div>
</div>
<%= link_to(new_cat_path, class: 'purchase-btn') do %>
  <span class='purchase-btn-text'>投稿する</span>
  <%= image_tag 'icon_camera.png' , size: '185x50' ,class: "purchase-btn-icon" %>
<% end %>

<%= render "shared/footer" %>

app/views/cats/new.html.erb
<div class="cat-post-contents">
  <header class="cat-post-header">
    <%= link_to image_tag('nyaking-map.png' , size: '200x80'), "/" %>

  </header>
  <div class="cat-post-main">
    <h2 class="cat-post-title"></h2>
    <%= form_with model: @cat, local: true do |f| %>

      <%= render 'shared/error_messages', model: f.object %>
      
      <div class="img-upload">
        <div class="weight-bold-text">
          画像 ※複数OK
          <span class="indispensable">必須</span> 
          <div class="click-upload">               
            <%= f.file_field :images, name: 'cat[images][]', id: 'cat-image' %>
          </div>
          <div class="image-list" id="image-list"></div>
        </div> 
      </div>
      
      <div class="nickname">
        <div class="cats-explain">
          <div class="weight-bold-text">
            メッセージ
          </div>
          <%= f.text_area :message, class:"cats-text", id:"cat-info",rows:"7" ,maxlength:"1000" %>
        </div>
      </div>

      <div class="area-detail">
        <div class="form">
          <div class="weight-bold-text">
            都道府県
            <span class="indispensable">必須</span>
            <span><%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"select-box", id:"prefecture"}) %></span>
          </div>
          
          <div class="weight-bold-text">
            市町村
            <span class="indispensable">必須</span>
          </div>
          <%= f.text_area :area, class:"area-text", id:"cat-area" %>
          <div class="weight-bold-text">
            会える場所
          </div>
          <%= f.text_area :place, class:"place-text", id:"cat-place" %>
        </div>
      </div>
      <div class="post-btn-contents">
        <%= f.submit "投稿する" ,class:"post-btn" %>
        <%=link_to 'もどる', root_path, class:"back-btn" %>
      </div>
    <% end %>
  </div>
  

  <footer class="cats-post-footer">
    <ul class="menu">
    </ul>
    <%= link_to image_tag('nyaking-map.png' , size: '200x80'), "/" %>
    <p class="inc">
       ©︎Nyaking-map,Inc.
    </p>
  </footer>
</div>

app/views/cats/prefecture.html.erb
<%= render "shared/header" %>
<%= render @cats, @comments %>
<%= paginate @cats %>
<%= render "shared/footer" %>

app/views/cats/search.html.erb
<%= render "shared/header" %>
<%= render @cats, @comments %>
<%= paginate @cats %>
<%= render "shared/footer" %>

app/views/cats/show.html.erb
<%= render "shared/header" %>

<div class="cat-show">
  <div class="cat-box">
    
    <div class="cat-explain-box">
      <% if user_signed_in? %>
        <% if current_user.liked_by?(@cat.id) %>
          <td>
            <%= link_to destroy_like_path(@cat), class: "like-link", method: :DELETE do %>
              <i class="fa fa-heart like-btn-unlike"></i>
            <% end %>
          </td>
          <%= @cat.likes.count %>
        <% else %>
          <td>
            <%= link_to create_like_path(@cat), calss: "like-link", method: :POST do %>
              <i class="fa fa-heart like-btn"></i>
            <% end %>
            <%= @cat.likes.count %>
          </td>
        <% end %>
      <% end %>
      <h2 class="name">
        <%= @cat.prefecture.name %> <%= @cat.area %> <%= @cat.place %>
      </h2>
    </div>

      画像がたくさんある場合はスライドで見れるよ
    <div class='cat-img-content'>
      <% @cat.images.each do |image|%>
        <%= image_tag image ,class:"cat-box-img" %>
      <% end %>
    </div>
    <div class="edit">
      <% if user_signed_in? %>
        <% if current_user.id == @cat.user_id %>
          <%= link_to '編集', edit_cat_path, method: :get, class: "item-red-btn" %>
          <%= link_to '削除', cat_path, method: :delete, class:'item-destroy' %>
        <% end %>
      <% end %>
    </div>
      
    
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-cat">ニックネーム</th>
          <td class="detail-value"><%= @cat.user.nickname %></td>
        </tr>
        <tr>
          <th class="detail-cat">メッセージ</th>
          <td class="detail-value"><%= @cat.message %></td>
        </tr>
        <tr>
          <th class="detail-cat">都道府県</th>
          <td class="detail-value"><%= @cat.prefecture.name %></td>
        </tr>
        <tr>
          <th class="detail-cat">市町村</th>
          <td class="detail-value"><%= @cat.area %></td>
        </tr>
        <tr>
          <th class="detail-cat">会えた場所</th>
          <td class="detail-value"><%= @cat.place %></td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="comment-box">
    <% if user_signed_in? %>
      <p>< コメント一覧 ></p>
      <div id='comment' >
        <% @comments.each do |comment| %>
          <div class='comment-area'>
            <div class="nickname"><%= comment.user.nickname %></div>          
            <div class="comment"><%= comment.text %></div>
            <div class="delete"><%= link_to "削除", cat_comment_path(@cat, comment), method: :delete, class: "comment-delete" %></div>      
          </div>
        <% end %>
      </div>
    
      <%= form_with model: [@cat, @comment], class: 'form', local: true do |f| %>
        <%= f.text_area :text, class: "comment-text", id: "comment-text" %>
        <%= f.button type: "submit", class: "comment-btn" do %>
          <%= image_tag "comment.png" ,class:"comment-flag-icon" ,width:"20",height:"25"%>
          <span>コメントする<span>
        <% end %>
      <% end %>
    <% end %>
  </div>
  <div class="links">
    <% if @cat.previous.present? %>
      <%= link_to "＜前の猫", cat_path(@cat.previous), class: "change-post-btn" %>
    <% end %>
    <% if @cat.next.present? %>
      <%= link_to "次の猫＞", cat_path(@cat.next), class: "change-post-btn" %>
    <% end %> 
  </div> 
</div>
<%= render "shared/footer" %>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>nyaking-map</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <script type="text/javascript" src="https://js.pay.jp/v1/"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <%= stylesheet_link_tag 'application', media: 'all'%>
  <%= javascript_pack_tag 'application' %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
</head>

<body>
  <%= yield %>
</body>

</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<%# 下部広告部分 %>
<div class='ad-footer-contents'>
  <div class='store-btn'>
    <%#= link_to image_tag("https://linkmaker.itunes.apple.com/ja-jp/badge-lrg.svg?releaseDate=2011-09-21&kind=iossoftware&bubble=ios_apps", class:"apple-btn"), "#" %>
    <%#= link_to image_tag("dl-android.png", class:"google-btn"), "#" %>
  </div>
</div>
<div class='footer'> 
  <%= link_to image_tag("nyaking-map.png", class:"logo-white"), root_path %>  
  <p class="inc">
    ©︎Nyaking-map,Inc.
  </p>
</div>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class='top-page-header'>
      
        
      
  <div class='search-bar-contents'>
    <%= link_to image_tag("nyaking-map.png", class:"cat-icon"), root_path %>
    <%= form_with(url: search_cats_path, local: true, method: :get, class: "search-form") do |f| %>
      <%= f.text_field :keyword, class: "input-box", placeholder: 'キーワードから探す'%>
      <%= f.button type: "submit", class: "search-button" do %>
        <%= image_tag "search.png", class:"search-icon" %>
      <% end %>
    <% end %>
    <%= search_form_for(@q, url: cat_prefecture_path, class: "search-form-2") do |f| %>
      <%= f.collection_select(:prefecture_id_eq, Prefecture.all, :id, :name, {prompt:"エリアで探す"}, {class:"type-list", id:"prefecture"}) %>
      <%= f.button type: "submit", class: "search-button" do %>
        <%= image_tag "search.png", class:"search-icon" %>
      <% end %>
    <% end %>
  </div>
  
  <div class='nav'>
    <ul class='lists-left'>
    <li><%= link_to 'おためしログイン', users_guest_sign_in_path, method: :post, class: "test" %></li>
      <% if user_signed_in? %>
        <li><%= link_to current_user.nickname, root_path, class: "user-nickname" %></li> 
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li> 
      <% else %>
        <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
        <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      <% end %>     
    </ul>

  </div>     
</header>

app/views/shared/_second-footer.html.erb
<footer class='second-fotter'> 
  <%= image_tag "nyaking-map.png", class:"second-fotter-logo"%>
</footer>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to image_tag("nyaking-map", class:"second-logo"), root_path %>
</header>